INSERT INTO `#__vikrentcar_config` (`param`,`setting`) VALUES ('mindaysadvance','0');
INSERT INTO `#__vikrentcar_config` (`param`,`setting`) VALUES ('maxdate','+2y');
INSERT INTO `#__vikrentcar_config` (`param`,`setting`) VALUES ('firstwday','0');
INSERT INTO `#__vikrentcar_config` (`param`,`setting`) VALUES ('charatsfilter','0');
INSERT INTO `#__vikrentcar_config` (`param`,`setting`) VALUES ('damageshowtype','3');
INSERT INTO `#__vikrentcar_config` (`param`,`setting`) VALUES ('thumbswidth','200');
INSERT INTO `#__vikrentcar_config` (`param`, `setting`) VALUES('invoiceinum', '0');
INSERT INTO `#__vikrentcar_config` (`param`, `setting`) VALUES('invoicesuffix', '/WEB');
INSERT INTO `#__vikrentcar_config` (`param`, `setting`) VALUES('invcompanyinfo', '');
INSERT INTO `#__vikrentcar_config` (`param`, `setting`) VALUES('icalkey', FLOOR(100 + (RAND() * 900)));
ALTER TABLE `#__vikrentcar_places` ADD COLUMN `defaulttime` varchar(16) DEFAULT NULL;
ALTER TABLE `#__vikrentcar_places` ADD COLUMN `ordering` int(10) NOT NULL DEFAULT 1;
ALTER TABLE `#__vikrentcar_seasons` ADD COLUMN `year` int(5) DEFAULT NULL;
ALTER TABLE `#__vikrentcar_seasons` ADD COLUMN `idprices` varchar(256) DEFAULT NULL;
ALTER TABLE `#__vikrentcar_seasons` ADD COLUMN `promo` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__vikrentcar_seasons` ADD COLUMN `promotxt` text DEFAULT NULL;
ALTER TABLE `#__vikrentcar_seasons` ADD COLUMN `promodaysadv` int(5) DEFAULT NULL;
ALTER TABLE `#__vikrentcar_cars` ADD COLUMN `short_info` varchar(512) DEFAULT NULL;
ALTER TABLE `#__vikrentcar_cars` ADD COLUMN `params` text DEFAULT NULL;
ALTER TABLE `#__vikrentcar_orders` ADD COLUMN `paymentlog` text DEFAULT NULL;
ALTER TABLE `#__vikrentcar_orders` ADD COLUMN `lang` varchar(10) DEFAULT NULL;
ALTER TABLE `#__vikrentcar_orders` ADD COLUMN `country` varchar(5) DEFAULT NULL;
ALTER TABLE `#__vikrentcar_orders` ADD COLUMN `carindex` int(5) DEFAULT NULL;
ALTER TABLE `#__vikrentcar_busy` ADD COLUMN `stop_sales` tinyint(1) NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS `#__vikrentcar_oohfees` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT, `oohname` varchar(128) NOT NULL DEFAULT 'Out of Hours', `pickcharge` decimal(12,2) DEFAULT NULL, `dropcharge` decimal(12,2) DEFAULT NULL, `maxcharge` decimal(12,2) DEFAULT NULL, `idcars` varchar(256) DEFAULT NULL, `from` int(6) NOT NULL DEFAULT 0, `to` int(6) NOT NULL DEFAULT 1, `type` tinyint(1) NOT NULL DEFAULT 1, `idiva` int(10) DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
CREATE TABLE IF NOT EXISTS `#__vikrentcar_oohfees_locxref` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT, `idooh` int(10) DEFAULT NULL, `idlocation` int(10) DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
CREATE TABLE IF NOT EXISTS `#__vikrentcar_countries` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT, `country_name` char(64) DEFAULT NULL, `country_3_code` char(3) DEFAULT NULL, `country_2_code` char(2) DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
INSERT INTO `#__vikrentcar_countries` (`country_name`, `country_3_code`, `country_2_code`) VALUES
('Afghanistan', 'AFG', 'AF'),
('Albania', 'ALB', 'AL'),
('Algeria', 'DZA', 'DZ'),
('American Samoa', 'ASM', 'AS'),
('Andorra', 'AND', 'AD'),
('Angola', 'AGO', 'AO'),
('Anguilla', 'AIA', 'AI'),
('Antarctica', 'ATA', 'AQ'),
('Antigua and Barbuda', 'ATG', 'AG'),
('Argentina', 'ARG', 'AR'),
('Armenia', 'ARM', 'AM'),
('Aruba', 'ABW', 'AW'),
('Australia', 'AUS', 'AU'),
('Austria', 'AUT', 'AT'),
('Azerbaijan', 'AZE', 'AZ'),
('Bahamas', 'BHS', 'BS'),
('Bahrain', 'BHR', 'BH'),
('Bangladesh', 'BGD', 'BD'),
('Barbados', 'BRB', 'BB'),
('Belarus', 'BLR', 'BY'),
('Belgium', 'BEL', 'BE'),
('Belize', 'BLZ', 'BZ'),
('Benin', 'BEN', 'BJ'),
('Bermuda', 'BMU', 'BM'),
('Bhutan', 'BTN', 'BT'),
('Bolivia', 'BOL', 'BO'),
('Bosnia and Herzegowina', 'BIH', 'BA'),
('Botswana', 'BWA', 'BW'),
('Bouvet Island', 'BVT', 'BV'),
('Brazil', 'BRA', 'BR'),
('British Indian Ocean Territory', 'IOT', 'IO'),
('Brunei Darussalam', 'BRN', 'BN'),
('Bulgaria', 'BGR', 'BG'),
('Burkina Faso', 'BFA', 'BF'),
('Burundi', 'BDI', 'BI'),
('Cambodia', 'KHM', 'KH'),
('Cameroon', 'CMR', 'CM'),
('Canada', 'CAN', 'CA'),
('Cape Verde', 'CPV', 'CV'),
('Cayman Islands', 'CYM', 'KY'),
('Central African Republic', 'CAF', 'CF'),
('Chad', 'TCD', 'TD'),
('Chile', 'CHL', 'CL'),
('China', 'CHN', 'CN'),
('Christmas Island', 'CXR', 'CX'),
('Cocos (Keeling) Islands', 'CCK', 'CC'),
('Colombia', 'COL', 'CO'),
('Comoros', 'COM', 'KM'),
('Congo', 'COG', 'CG'),
('Cook Islands', 'COK', 'CK'),
('Costa Rica', 'CRI', 'CR'),
('Cote D''Ivoire', 'CIV', 'CI'),
('Croatia', 'HRV', 'HR'),
('Cuba', 'CUB', 'CU'),
('Cyprus', 'CYP', 'CY'),
('Czech Republic', 'CZE', 'CZ'),
('Denmark', 'DNK', 'DK'),
('Djibouti', 'DJI', 'DJ'),
('Dominica', 'DMA', 'DM'),
('Dominican Republic', 'DOM', 'DO'),
('East Timor', 'TMP', 'TP'),
('Ecuador', 'ECU', 'EC'),
('Egypt', 'EGY', 'EG'),
('El Salvador', 'SLV', 'SV'),
('Equatorial Guinea', 'GNQ', 'GQ'),
('Eritrea', 'ERI', 'ER'),
('Estonia', 'EST', 'EE'),
('Ethiopia', 'ETH', 'ET'),
('Falkland Islands (Malvinas)', 'FLK', 'FK'),
('Faroe Islands', 'FRO', 'FO'),
('Fiji', 'FJI', 'FJ'),
('Finland', 'FIN', 'FI'),
('France', 'FRA', 'FR'),
('French Guiana', 'GUF', 'GF'),
('French Polynesia', 'PYF', 'PF'),
('French Southern Territories', 'ATF', 'TF'),
('Gabon', 'GAB', 'GA'),
('Gambia', 'GMB', 'GM'),
('Georgia', 'GEO', 'GE'),
('Germany', 'DEU', 'DE'),
('Ghana', 'GHA', 'GH'),
('Gibraltar', 'GIB', 'GI'),
('Greece', 'GRC', 'GR'),
('Greenland', 'GRL', 'GL'),
('Grenada', 'GRD', 'GD'),
('Guadeloupe', 'GLP', 'GP'),
('Guam', 'GUM', 'GU'),
('Guatemala', 'GTM', 'GT'),
('Guinea', 'GIN', 'GN'),
('Guinea-bissau', 'GNB', 'GW'),
('Guyana', 'GUY', 'GY'),
('Haiti', 'HTI', 'HT'),
('Heard and Mc Donald Islands', 'HMD', 'HM'),
('Honduras', 'HND', 'HN'),
('Hong Kong', 'HKG', 'HK'),
('Hungary', 'HUN', 'HU'),
('Iceland', 'ISL', 'IS'),
('India', 'IND', 'IN'),
('Indonesia', 'IDN', 'ID'),
('Iran (Islamic Republic of)', 'IRN', 'IR'),
('Iraq', 'IRQ', 'IQ'),
('Ireland', 'IRL', 'IE'),
('Israel', 'ISR', 'IL'),
('Italy', 'ITA', 'IT'),
('Jamaica', 'JAM', 'JM'),
('Japan', 'JPN', 'JP'),
('Jordan', 'JOR', 'JO'),
('Kazakhstan', 'KAZ', 'KZ'),
('Kenya', 'KEN', 'KE'),
('Kiribati', 'KIR', 'KI'),
('Korea, Democratic People''s Republic of', 'PRK', 'KP'),
('Korea, Republic of', 'KOR', 'KR'),
('Kuwait', 'KWT', 'KW'),
('Kyrgyzstan', 'KGZ', 'KG'),
('Lao People''s Democratic Republic', 'LAO', 'LA'),
('Latvia', 'LVA', 'LV'),
('Lebanon', 'LBN', 'LB'),
('Lesotho', 'LSO', 'LS'),
('Liberia', 'LBR', 'LR'),
('Libyan Arab Jamahiriya', 'LBY', 'LY'),
('Liechtenstein', 'LIE', 'LI'),
('Lithuania', 'LTU', 'LT'),
('Luxembourg', 'LUX', 'LU'),
('Macau', 'MAC', 'MO'),
('Macedonia, The Former Yugoslav Republic of', 'MKD', 'MK'),
('Madagascar', 'MDG', 'MG'),
('Malawi', 'MWI', 'MW'),
('Malaysia', 'MYS', 'MY'),
('Maldives', 'MDV', 'MV'),
('Mali', 'MLI', 'ML'),
('Malta', 'MLT', 'MT'),
('Marshall Islands', 'MHL', 'MH'),
('Martinique', 'MTQ', 'MQ'),
('Mauritania', 'MRT', 'MR'),
('Mauritius', 'MUS', 'MU'),
('Mayotte', 'MYT', 'YT'),
('Mexico', 'MEX', 'MX'),
('Micronesia, Federated States of', 'FSM', 'FM'),
('Moldova, Republic of', 'MDA', 'MD'),
('Monaco', 'MCO', 'MC'),
('Mongolia', 'MNG', 'MN'),
('Montserrat', 'MSR', 'MS'),
('Morocco', 'MAR', 'MA'),
('Mozambique', 'MOZ', 'MZ'),
('Myanmar', 'MMR', 'MM'),
('Namibia', 'NAM', 'NA'),
('Nauru', 'NRU', 'NR'),
('Nepal', 'NPL', 'NP'),
('Netherlands', 'NLD', 'NL'),
('Netherlands Antilles', 'ANT', 'AN'),
('New Caledonia', 'NCL', 'NC'),
('New Zealand', 'NZL', 'NZ'),
('Nicaragua', 'NIC', 'NI'),
('Niger', 'NER', 'NE'),
('Nigeria', 'NGA', 'NG'),
('Niue', 'NIU', 'NU'),
('Norfolk Island', 'NFK', 'NF'),
('Northern Mariana Islands', 'MNP', 'MP'),
('Norway', 'NOR', 'NO'),
('Oman', 'OMN', 'OM'),
('Pakistan', 'PAK', 'PK'),
('Palau', 'PLW', 'PW'),
('Panama', 'PAN', 'PA'),
('Papua New Guinea', 'PNG', 'PG'),
('Paraguay', 'PRY', 'PY'),
('Peru', 'PER', 'PE'),
('Philippines', 'PHL', 'PH'),
('Pitcairn', 'PCN', 'PN'),
('Poland', 'POL', 'PL'),
('Portugal', 'PRT', 'PT'),
('Puerto Rico', 'PRI', 'PR'),
('Qatar', 'QAT', 'QA'),
('Reunion', 'REU', 'RE'),
('Romania', 'ROM', 'RO'),
('Russian Federation', 'RUS', 'RU'),
('Rwanda', 'RWA', 'RW'),
('Saint Kitts and Nevis', 'KNA', 'KN'),
('Saint Lucia', 'LCA', 'LC'),
('Saint Vincent and the Grenadines', 'VCT', 'VC'),
('Samoa', 'WSM', 'WS'),
('San Marino', 'SMR', 'SM'),
('Sao Tome and Principe', 'STP', 'ST'),
('Saudi Arabia', 'SAU', 'SA'),
('Senegal', 'SEN', 'SN'),
('Seychelles', 'SYC', 'SC'),
('Sierra Leone', 'SLE', 'SL'),
('Singapore', 'SGP', 'SG'),
('Slovakia (Slovak Republic)', 'SVK', 'SK'),
('Slovenia', 'SVN', 'SI'),
('Solomon Islands', 'SLB', 'SB'),
('Somalia', 'SOM', 'SO'),
('South Africa', 'ZAF', 'ZA'),
('South Georgia and the South Sandwich Islands', 'SGS', 'GS'),
('Spain', 'ESP', 'ES'),
('Sri Lanka', 'LKA', 'LK'),
('St. Helena', 'SHN', 'SH'),
('St. Pierre and Miquelon', 'SPM', 'PM'),
('Sudan', 'SDN', 'SD'),
('Suriname', 'SUR', 'SR'),
('Svalbard and Jan Mayen Islands', 'SJM', 'SJ'),
('Swaziland', 'SWZ', 'SZ'),
('Sweden', 'SWE', 'SE'),
('Switzerland', 'CHE', 'CH'),
('Syrian Arab Republic', 'SYR', 'SY'),
('Taiwan', 'TWN', 'TW'),
('Tajikistan', 'TJK', 'TJ'),
('Tanzania, United Republic of', 'TZA', 'TZ'),
('Thailand', 'THA', 'TH'),
('Togo', 'TGO', 'TG'),
('Tokelau', 'TKL', 'TK'),
('Tonga', 'TON', 'TO'),
('Trinidad and Tobago', 'TTO', 'TT'),
('Tunisia', 'TUN', 'TN'),
('Turkey', 'TUR', 'TR'),
('Turkmenistan', 'TKM', 'TM'),
('Turks and Caicos Islands', 'TCA', 'TC'),
('Tuvalu', 'TUV', 'TV'),
('Uganda', 'UGA', 'UG'),
('Ukraine', 'UKR', 'UA'),
('United Arab Emirates', 'ARE', 'AE'),
('United Kingdom', 'GBR', 'GB'),
('United States', 'USA', 'US'),
('United States Minor Outlying Islands', 'UMI', 'UM'),
('Uruguay', 'URY', 'UY'),
('Uzbekistan', 'UZB', 'UZ'),
('Vanuatu', 'VUT', 'VU'),
('Vatican City State (Holy See)', 'VAT', 'VA'),
('Venezuela', 'VEN', 'VE'),
('Viet Nam', 'VNM', 'VN'),
('Virgin Islands (British)', 'VGB', 'VG'),
('Virgin Islands (U.S.)', 'VIR', 'VI'),
('Wallis and Futuna Islands', 'WLF', 'WF'),
('Western Sahara', 'ESH', 'EH'),
('Yemen', 'YEM', 'YE'),
('The Democratic Republic of Congo', 'DRC', 'DC'),
('Zambia', 'ZMB', 'ZM'),
('Zimbabwe', 'ZWE', 'ZW'),
('East Timor', 'XET', 'XE'),
('Jersey', 'XJE', 'XJ'),
('St. Barthelemy', 'XSB', 'XB'),
('St. Eustatius', 'XSE', 'XU'),
('Canary Islands', 'XCA', 'XC'),
('Serbia', 'SRB', 'RS'),
('Sint Maarten (French Antilles)', 'MAF', 'MF'),
('Sint Maarten (Netherlands Antilles)', 'SXM', 'SX');